/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import cookieManager from "strapi-plugin-cookie-manager/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import publisher from "strapi-plugin-publisher/strapi-admin";
import restCache from "strapi-plugin-rest-cache/strapi-admin";
import tagsinput from "strapi-plugin-tagsinput/strapi-admin";
import timezoneSelect from "strapi-plugin-timezone-select/strapi-admin";
import translate from "strapi-plugin-translate/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    "drag-drop-content-types": dragDropContentTypes,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    "cookie-manager": cookieManager,
    "import-export-entries": importExportEntries,
    "multi-select": multiSelect,
    navigation: navigation,
    publisher: publisher,
    "rest-cache": restCache,
    tagsinput: tagsinput,
    "timezone-select": timezoneSelect,
    translate: translate,
  },
});
